Kan 6 harsha payment
AYS-At-Your-Service/AYS pull request #10
Opened 2024-01-25 17:53 UTC by Harsha1varthan

2024-01-31 17:27 UTC, aravindv97 commented
@Harsha1varthan, pls add a short description similar to other PRs

2024-02-02 15:09 UTC, aravindv97 requested changes

2024-02-02 15:09 UTC, aravind-digitech commented on Frontend/src/App.css
> +    box-shadow:  4px 6px rgba(15, 15, 15, 0.08)
use variables

2024-02-02 15:09 UTC, aravind-digitech commented on Frontend/src/App.jsx
pls revert changes in this file

2024-02-02 15:09 UTC, aravindv97 commented on Frontend/src/Payment/Checkout.jsx
> +                <h1>Checkout</h1>
use constants as in https://github.com/AYS-At-Your-Service/AYS/pull/13/files#diff-c2c392d453cc978fcfed88aae84cdeb1b2ce75f60d0bb32f26cc6e821ab39a7b

2024-02-02 15:09 UTC, aravindv97 commented on Frontend/src/Payment/Payment.jsx
> +                            <p>Pay via UPI Id</p>
use constants

2024-02-02 15:09 UTC, aravindv97 commented on Frontend/src/assets/location.webp
pls remove all bin files

2024-02-06 17:09 UTC, aravindv97 commented
pls re raise PR once the changes are done

2024-02-06 17:09 UTC, closed without merging

2024-02-07 01:07 UTC, Harsha1varthan commented
Once It was done, I would raise the PR

On Tue, Feb 6, 2024, 22:40 aravindv97 ***@***.***> wrote:

> pls re raise PR once the changes are done
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AYS-At-Your-Service/AYS/pull/10#issuecomment-1930388765>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3ZKSYOGUQDQ3ALO5U7XHRDYSJPXBAVCNFSM6AAAAABCK53LQGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZQGM4DQNZWGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>