KAN 2 MURALI PREFERED TIMESLOT
AYS-At-Your-Service/AYS pull request #12
Opened 2024-01-31 17:16 UTC by Murali03M

1) PreferedTImeSlot component will return selected date and time.

Demo 

https://github.com/AYS-At-Your-Service/AYS/assets/73110751/530c38c6-2d3a-4f12-96a7-821dc9766334

2024-02-02 14:07 UTC, aravindv97 requested changes

2024-02-02 14:07 UTC, aravind-digitech commented on Frontend/components/Prefered-timeslot.jsx
> +          <h3>Get a serivce later</h3>
pls save all constants (strings, numbers) in a separate preferred-timeslot.consts.js file and import it for use

2024-02-02 14:07 UTC, aravind-digitech commented on Frontend/components/Prefered-timeslot.jsx
pls create a folder called preferredTimeSlot under components and move this and the css file there

2024-02-02 14:07 UTC, aravindv97 commented on Frontend/src/App.jsx
pls revert all changes in this file

2024-02-03 00:41 UTC, Murali03M commented on Frontend/components/Prefered-timeslot.jsx
> +          <h3>Get a serivce later</h3>
created the new file and constants are exported from there

2024-02-03 00:41 UTC, Murali03M commented on Frontend/components/Prefered-timeslot.jsx
folder was created

2024-02-03 00:42 UTC, Murali03M commented on Frontend/src/App.jsx
yeah , it's done

2024-02-03 14:25 UTC, aravindv97 approved these changes

2024-02-05 17:19 UTC, GREEDnim approved these changes

2024-02-05 17:35 UTC, merged