Kan 6 harsha payment
AYS-At-Your-Service/AYS pull request #19
Opened 2024-02-09 16:04 UTC by Harsha1varthan

#CheckOut page

![AYS(1)](https://github.com/AYS-At-Your-Service/AYS/assets/116566369/976e1c53-2c8a-4c49-99db-042311a2ac72)

##Media Queries were Added

2024-02-09 17:27 UTC, aravindv97 commented
I guess latest changes are missing in this branch, pls create a new branch from Development and add your changes there

2024-02-09 17:30 UTC, Harsha1varthan commented
Okay bro

On Fri, Feb 9, 2024, 22:57 aravindv97 ***@***.***> wrote:

> I guess latest changes are missing in this branch, pls create a new branch
> from Development and add your changes there
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AYS-At-Your-Service/AYS/pull/19#issuecomment-1936312425>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3ZKSYLW5GAZ3N4EEPCF6K3YSZMAXAVCNFSM6AAAAABDBWNNJSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZWGMYTENBSGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-09 17:30 UTC, aravindv97 requested changes

2024-02-09 17:30 UTC, aravindv97 commented on Frontend/src/App.css
pls move all the changes to a css module in the component folder as in https://github.com/AYS-At-Your-Service/AYS/pull/13/files#diff-71ff0a73d0033410b9ff162a070eeb8a2f531418c2180812041b998676c3c4a4

2024-02-09 17:30 UTC, aravindv97 commented on Frontend/src/App.jsx
pls revert changes in this file

2024-02-09 17:30 UTC, aravindv97 commented on Frontend/src/Payment/Checkout.jsx
pls import the css module and use it to apply styles like `inputStyles['search-box-container']` ref: https://github.com/AYS-At-Your-Service/AYS/pull/13/files#diff-4efee8ce3f0bbe6048ca338557b4d41369d3e6a059308a8907cbfecdde11e04f

2024-02-09 17:30 UTC, aravindv97 commented on Frontend/src/Payment/Checkout.jsx
> +                  <h4>Send Booking Details</h4>
Use constants by importing a constants file like `{consts.STATICPLACEHOLDER}` ref: https://github.com/AYS-At-Your-Service/AYS/pull/13/files#diff-4efee8ce3f0bbe6048ca338557b4d41369d3e6a059308a8907cbfecdde11e04f

2024-02-09 17:30 UTC, aravindv97 commented on Frontend/src/Payment/Checkout.jsx
Components should be under Frontend/src/components

2024-02-13 18:04 UTC, aravindv97 commented
Re raised new PR hence closing this one

2024-02-13 18:04 UTC, closed without merging