Kan 6 harsha payment
AYS-At-Your-Service/AYS pull request #20
Opened 2024-02-10 11:35 UTC by Harsha1varthan

#Added Every Changes according to the Request

2024-02-13 18:29 UTC, aravindv97 requested changes

2024-02-13 18:29 UTC, aravindv97 commented on Frontend/src/States/state.js
pls move this file to the particular component's folder

2024-02-13 18:29 UTC, aravindv97 commented on Frontend/src/components/CheckOut/constants/constant.js
> +export const LandLine = 91
use CAPS for names eg LANDLINE

2024-02-13 18:29 UTC, aravindv97 commented on Frontend/src/css/Input.module.css
revert changes in all files under css folder

2024-02-13 18:29 UTC, aravindv97 commented on Frontend/src/App.css
pls move these changes to index.css file and also follow naming convention like checkOutMain-least-padding

2024-02-13 18:29 UTC, aravindv97 commented on Frontend/src/index.css
> +  --base-font-size: 20px;
pls avoid changes to existing props, pls create one with component prefix if required eg innerbox-base-font-size

2024-02-13 18:30 UTC, aravindv97 commented
@Murali03M @Harsha1varthan @GREEDnim pls review and approve

2024-02-15 18:20 UTC, aravindv97 approved these changes

2024-02-27 16:39 UTC, Sathish111j approved these changes

2024-02-27 17:53 UTC, aravindv97 approved these changes

2024-02-28 16:43 UTC, jayakanthansubramani approved these changes

2024-02-28 16:45 UTC, merged