Kan 5 sathish listing vendors
AYS-At-Your-Service/AYS pull request #22
Opened 2024-02-14 17:54 UTC by Sathish111j

Filtering and Search of vendor components has been created

![Screenshot (44)](https://github.com/AYS-At-Your-Service/AYS/assets/92447689/c1ed18df-26d5-4e6d-b043-e8b87191abbd)

2024-02-15 17:57 UTC, aravind-digitech requested changes
Overall: 

1. pls look into file naming conventions
2. creating and using constants imported from another file in component jsx

2024-02-15 17:57 UTC, aravindv97 commented on Frontend/src/App.jsx
pls revert changes

2024-02-15 17:57 UTC, aravind-digitech commented on Frontend/src/components/filterAndSearchVendor/Products/Product.css
pls rename file to product.module.css

2024-02-15 17:57 UTC, aravindv97 commented on Frontend/src/components/filterAndSearchVendor/Recommended/Recommended.css
rename

2024-02-15 17:57 UTC, aravindv97 commented on Frontend/src/components/filterAndSearchVendor/Recommended/Recommended.jsx
store strings in constant file like in Frontend/src/components/header/header.consts.js

2024-02-15 17:57 UTC, aravindv97 commented on Frontend/src/components/filterAndSearchVendor/SearchAndSort/searchAndSort.css
rename

2024-02-15 17:57 UTC, aravindv97 commented on Frontend/src/components/filterAndSearchVendor/SearchAndSort/searchAndSort.jsx
constants

2024-02-15 17:57 UTC, aravindv97 commented on Frontend/src/components/filterAndSearchVendor/Sidebar/AcceptedOrders/AcceptedOrders.jsx
constants

2024-02-21 07:04 UTC, Sathish111j commented on Frontend/src/App.jsx
changes has been made

2024-02-21 07:04 UTC, Sathish111j commented on Frontend/src/components/filterAndSearchVendor/Products/Product.css
done

2024-02-21 07:04 UTC, Sathish111j commented on Frontend/src/components/filterAndSearchVendor/Recommended/Recommended.css
rename done

2024-02-21 07:05 UTC, Sathish111j commented on Frontend/src/components/filterAndSearchVendor/Recommended/Recommended.jsx
contants have been put in other webiste

2024-02-21 07:05 UTC, Sathish111j commented on Frontend/src/components/filterAndSearchVendor/SearchAndSort/searchAndSort.css
done

2024-02-21 07:05 UTC, Sathish111j commented on Frontend/src/components/filterAndSearchVendor/SearchAndSort/searchAndSort.jsx
done

2024-02-21 07:05 UTC, Sathish111j commented on Frontend/src/components/filterAndSearchVendor/Sidebar/AcceptedOrders/AcceptedOrders.jsx
done

2024-02-21 07:06 UTC, Sathish111j commented
Alll required changes have been made and PR has been raised

2024-02-21 08:22 UTC, Sathish111j commented
Alll required changes have been made and PR has been raised

2024-02-27 16:42 UTC, aravindv97 approved these changes

2024-02-27 16:48 UTC, jayakanthansubramani approved these changes

2024-02-27 17:18 UTC, merged